### ISSUE TITLE
Different installation location

### ISSUE THREAD

**Issue by ghost** [tin2tin/Script_Editing#1]
Hi, thanks for this nice template. I've tried to install it but did not succeed. Could it be that my installation folder is not C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\startup\bl_app_templates_system that causes the problem?

Also two suggestions:
- Why "remove -main". Couldn't the folder not be named as such (without -main)?
- In blender 2.91 there seems to be no Script Editing' entry anymore in the Welcome pop-up. I suppose It could also be done by starting Blender in Default template and  selecting the Scripting workspace?

Thanks for all the work.

**Comment by tin2tin** [comment]
I made an installation video for you here: https://www.youtube.com/watch?v=ufSyony6eRE

> Hi, thanks for this nice template. I've tried to install it but did not succeed. Could it be that my installation folder is not C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\startup\bl_app_templates_system that causes the problem?

Search for this folder: bl_app_templates_system from the main blender installation folder and add the Script Editing folder - unzipped - to this folder. The files needs to be one level down from the main folder. When the folder is in place re/start Blender.

> * Why "remove -main". Couldn't the folder not be named as such (without -main)?

The folder name will be the workspace name - maybe it isn't, you could test this. 

> * In blender 2.91 there seems to be no Script Editing' entry anymore in the Welcome pop-up. I suppose It could also be done by starting Blender in Default template and  selecting the Scripting workspace?

Scripting workspace is the default workspace and unrelated to the Script Editing workspace. If you do not see it in the Welcome screen, it is not installed properly, so see above to solve that.

Let me know how it works out for you?

**Comment by ghost** [comment]
Thanks for the video. It works! Probably, it worked already the first time but I made a stupid mistake by starting up a different Blender version. It does not matter where the Blender app is installed (C-drive, D-drive, Program Files ...). I did the test to leave "main" in the folder name. The workspace tab name is correct (Script Editing); only in the welcome screen you see the original name (Script Editing main). I'm going to experiment with the script editing workspace and the enabled addons. So some learning ahead. Thanks again for the great work.

**Comment by tin2tin** [comment]
Great, thanks!

**Comment by ghost** [comment]
Hello again. I saw that the preset addons are stored in the default location (c:\users\...).
- Is it possible to store the addons in a custom location ; set by Preferences > File Path > Scripts.
- The default location (c:\users\ ...\appData) is a hidden folder in Windows. I cannot see this folder in the Blender File Browser. Do you know a solution?
- What is your workflow for storing addons?

**Comment by tin2tin** [comment]
It is installing the add-ons as they're normally installed in Blender. 

To unhide files in win 10: https://support.microsoft.com/en-us/help/4028316/windows-view-hidden-files-and-folders-in-windows-10

In Blender:
![image](https://user-images.githubusercontent.com/1322593/95679771-4d6f2000-0bd5-11eb-8d68-3ccedf9213a5.png)

Then you can go to the folder with all the installed add-ons:
C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons

I just use the Preferences region, which is exposed in the Script Editing workspace - there is an install button there:
![image](https://user-images.githubusercontent.com/1322593/95679794-7f808200-0bd5-11eb-8dae-d3942015a7e0.png)

**Comment by ghost** [comment]
Thanks. On further testing, I discover that the startup.blend file is now located in a folder c:\users\...\AppData\Roaming\Blender Foundation\Blender\2.91\config\Script_Editing_main\startup.blend and not in the folder above. Is this correct? I did not find a regular startup.blend file in the config-folder. Maybe I have deleted it. Anyway;  to have a regular startup (eg layout workspace), I had to save the workspace (File > Defaults > Save startup). This created a second startup.blend in the folder above. Also, I cannot change the Preferences panel (middle of Scrip editing workspace) to show the addons by default. I always have to expand the menubar at the left and click on Addons. Saving this state as startup doesn't seem to have any effect.

**Comment by tin2tin** [comment]
To change the startup.blend, I open that file, de the changes and overwrite the file. Here the Preferences are opened in addon "mode". If you save factory setting it seems like additional .blend files are saved and used from that point on, so you'll properly need to delete those to get the original startup.blend to work again.
